version: '3.8'
services:
  db:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db:/var/lib/postgresql/data
      - ./server/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - 5433:5432

  canvas:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      - CANVAS_DB_HOST=db
      - CANVAS_DB_DATABASE_NAME=candata
      - CANVAS_DB_USER=postgres
      - CANVAS_DB_PASSWORD=password
      - CANVAS_URL="http://canvas.opencan.org:3000"
    ports:
      - 8080:8080

volumes:
  db:
    driver: local
