version: '3.8'
services:
  db:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db:/var/lib/postgresql/data
      - ./server/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - 5433:5432

  canvas:
    image: canvas-server:0.1.0
    restart: always
    depends_on:
      - db
    ports:
      - 8085:8080

volumes:
  db:
    driver: local
