name: build-server

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build canvas-server image
        uses: docker/build-push-action@v4
        with:
          push: false
